import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import { AutoConnect } from "thirdweb/react";
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { createThirdwebClient } from 'thirdweb';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <Header />
        <ConnectButton />
      </main>
    </div>
  );
};

function Header() {
  return (
    <header className="flex flex-col items-center mb-20 md:mb-20">
      <h1 className="text-2xl md:text-6xl font-semibold md:font-bold tracking-tighter mb-6 text-zinc-100">
        thirdweb{" "}
        <span className="inline-block -skew-x-6 text-blue-500"> RainbowKit </span>
        {" "}Portal
      </h1>

    </header>
  );
}


export default Home;
